--- # Config File
smtp:
  server: "email-smtp.us-east-1.amazonaws.com"
  recipients:
    - ayo@greystein.com
  from:
    - ayobama72@gmail.com
max_pages: 1
search:
  target_words:
    - "application"
    - "candidates"
    - "science"
    - "masters"